### ISSUE TITLE
Compilation flags to ensure small binary size?

### ISSUE THREAD

**Issue by wjakob** [pybind/pbtest#1]
There are a few compilation flags that make a huge difference with respect to unnecessary bloat in the resulting binaries when compiling stuff using pybind11. In particular, that is ``-fvisibility=hidden`` on GCC/Clang (>50% difference).

It's also good to turn on C++14 support if possible, since that pushes some precomputation to the compile phase. In CMake, I would just do:
```
      if (HAS_CPP14_FLAG)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
      elseif (HAS_CPP11_FLAG)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
      else()
        message(FATAL_ERROR "Unsupported compiler -- at least C++11 support is needed!")
      endif()
```
Is it possible to enable these flags here as well?

**Comment by SylvainCorlay** [comment]
Yes, we can easily add the -fvisibility flag easily for gcc and clang.

I don't know about HS_CPP14_FLAG yet.

**Comment by wjakob** [comment]
is it possible to test whether a compilation flag causes the compiler to error out? That's basically what this flag contains : whether "-std=c++14" is even a valid parameter.

**Comment by wjakob** [comment]
FYI: this repository is now referenced from the docs.

**Comment by SylvainCorlay** [comment]
> FYI: this repository is now referenced from the docs.

Cool. I will add the same license as pybind11 everywhere.

For the compiler flag, I was hoping that the [compiler object](https://docs.python.org/2/distutils/apiref.html) would have utilities to check if it exists but apparently not.

**Comment by wjakob** [comment]
A suggestion: you could call has_function with a dummy function and include the header file ``shared_mutex``, which only exists on C++14. If that works, and if the compiler is Clang or GCC, add "-std=c++14".

**Comment by SylvainCorlay** [comment]
Yes, this is what the `has_function` does. `has_flag` could be a call to `has_function` with a C++14-only includes list.

**Comment by wjakob** [comment]
just a ping on this ticket :) -- thanks, Wenzel

**Comment by SylvainCorlay** [comment]
I just got back from vacation.  I have got to prepare a talk for tonight but will give it a try tomorrow. In the meantime, I have a conda recipe for this repo in a different PR.

**Comment by SylvainCorlay** [comment]
@wjakob done. I also submitted a patch to cpython adding a `has_flag` method to `CCompiler`.

**Comment by wjakob** [comment]
Looks, great! Thank you.

**Comment by SylvainCorlay** [comment]
btw, I have not added `-fvisibility=hidden`, but you can do so if you want.

**Comment by wjakob** [comment]
Please do -- it makes a huge difference with regards to the size of the final binary. Not being super-familiar with setup.py conventions: if there is some kind of a debug mode for compiling binary extension modules, then that parameter could be omitted if the debug mode is specified.

**Comment by SylvainCorlay** [comment]
Done.
